sonar.projectKey=zmathmatos_fiap-soat-tech-challenge-infra-db
sonar.organization=zmathmatos
sonar.projectName=fiap-soat-tech-challenge-infra-db

sonar.sources=.
sonar.exclusions=**/.terraform/**,**/*.tfstate,**/*.tfstate.*,docs/**
